### Google Colabを利用する場合は、次のセルの全行の#を1つ削除して実行する

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

## データフレームへの読み込み
## Google DriveのColab Notebooksにダウンロードしたフォルダ(marketing)をセットすることを想定
#iPath = '/content/drive/MyDrive/Colab Notebooks/marketing/Chapter_5/in/'
#iFile=iPath+'datQpr.csv'

#!pip install nysol

#import pandas as pd
#import nysol.take as nt
#import os
#os.makedirs('out', exist_ok=True)

## QPRのデータを読み込む
#df = pd.read_csv(iFile)

In [1]:
import pandas as pd
import nysol.take as nt
import os
os.makedirs('out', exist_ok=True)

In [4]:
# コード 5.1 モニタ-商品の 2 部グラフを作成するコード
df = pd.read_csv('in/datQpr.csv')  # QPRのデータを読み込む

,モニタ,日付,購入先区分送信ID,店舗,業態,商品,購入数量,単価,金額,都道府県,...,小学生有無,中高生有無,大人有無,老人有無,曜日,大分類名,中分類名,小分類名,細分類名,業態名
0,00J,20140120,NaN,2,2,6JN,1,248.0,248.0,0,...,0,0,1,0,月,食品,加工食品,漬物・佃煮,漬物,コンビニエンスストア
1,00J,20140119,0CjU,D,1,u9,1,98.0,98.0,0,...,0,0,1,0,日,食品,生鮮食品,農産,その他農産,スーパー
2,00J,20140201,NaN,u,5,fEw,2,198.0,396.0,0,...,0,0,1,0,土,日用品,日用雑貨,住居用洗剤類,使い捨て紙クリーナー類,薬粧店・ドラッグストア
3,00J,20130826,NaN,2,2,2hn,4,62.0,248.0,0,...,0,0,1,0,月,食品,菓子類,アイスクリーム類,パーソナルアイスその他,コンビニエンスストア
4,00J,20130907,6bGe,D,1,fZh,1,198.0,198.0,0,...,0,0,1,0,土,食品,加工食品,惣菜類,サラダ,スーパー
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226298,zA,20140103,NaN,7,2,a,1,168.0,168.0,0,...,0,0,1,1,金,食品,加工食品,パン・シリアル類,食パン,コンビニエンスストア
226299,zA,20130915,NaN,7,2,51U,1,138.0,138.0,0,...,0,0,1,1,日,食品,加工食品,パン・シリアル類,食パン,コンビニエンスストア
226300,zA,20140228,NaN,7,2,07W,1,105.0,105.0,0,...,0,0,1,1,金,食品,加工食品,パン・シリアル類,食パン,コンビニエンスストア
226301,zA,20140306,NaN,7,2,a,1,168.0,168.0,0,...,0,0,1,1,木,食品,加工食品,パン・シリアル類,食パン,コンビニエンスストア
226302,zA,20131026,NaN,7,2,a,1,168.0,168.0,0,...,0,0,1,1,土,食品,加工食品,パン・シリアル類,食パン,コンビニエンスストア

In [2]:
df = df[df['業態名'] == 'スーパー']  # スーパーのみ選択
# 日本茶・麦茶ドリンクを買っているモニタ一覧を作る
sel = df[df['細分類名'] == '日本茶・麦茶ドリンク']['モニタ'].drop_duplicates()
# そのモニタのデータのみを選択する
df = df[df['モニタ'].isin(sel)]
# 全員が日本茶・麦茶ドリンクを購入しており、
# そのような商品を加えても意味がないので削除しておく
bigraph = df[df['細分類名'] != '日本茶・麦茶ドリンク']
# モニタ項目と商品項目とを選択し、重複を削除すれば２部グラフの出来上がり
bigraph = df[['モニタ', '商品']].drop_duplicates()
# CSVに保存しておく
bigraph.to_csv('out/bigraph.csv', index=False)

print(bigraph)
print('モニタ数:', len(sel))
print('商品数:', len(bigraph['商品'].drop_duplicates()))
print('2部グラフ全行数:', len(bigraph))

        モニタ    商品
1123    04g    5X
1127    04g    4r
1130    04g   09k
1131    04g    ow
1134    04g    1N
...     ...   ...
222989   uy    ao
222990   uy  0y0U
222991   uy    1K
222992   uy   muI
222993   uy    hK

[43451 rows x 2 columns]
モニタ数: 192
商品数: 21815
2部グラフ全行数: 43451

In [3]:
# コード 5.2 極大 2 部クリークを列挙するコード
# ２〜３分かかる
nt.mbiclique(ei="out/bigraph.csv", ef="モニタ,商品", o="out/biclique.csv").run()
# 極大2部クリークの結果を閲覧する
biclique = pd.read_csv('out/biclique.csv')
biclique

,モニタ%0,商品%1,size1,size2
0,04g,0 00 010 016 018T 01R 01pX 01s 01v 01y8 02R 02...,1,590
1,04g 069,0 01R 01s 07E 0S 0Z 0e 1B 1Mi 1y6 2 2N 2j 2k 2...,2,43
2,04g 069 06I,0 1B 2N 2j 3o 5 P8 n8,3,8
3,04g 069 06I 09a 0A2 0Ac 0C1 0CQ 0Ia 0RU 0S2 0S...,0,96,1
4,04g 069 06I 0Ac 0SV 0hX 17n 19d 2V9 2jS 2rF 3B...,1B,22,1
...,...,...,...,...
62483,rr ut,0 0U 0X 4H 7s L qW,2,7
62484,tf,0 00CX 00P 01Z 01j 02N 02z 039 03e 04f 04xf 05...,1,475
62485,tf ut,0 01Z 05n 06y 0G 0H 0Hn 0K 0T 0V 0X 0j6 0m 0uV...,2,42
62486,ut,0 00j 00r 018 01Z 025 028 02T 03NW 03rX 04 05 ...,1,705
62487,uy,0 0vd 0y0U 1K 2e2 2i4 4 5vb 6KT 7h2 8N 9h C5W ...,1,27

In [4]:
# コード 5.3 モニタのサイズが 10 以上、商品のサイズが 3 以上のバイクラスタを選択する
# l=にモニタ集合と商品集合の最小サイズを指定することが可能
nt.mbiclique(ei='out/bigraph.csv', ef='モニタ,商品',
             l='10,3', o='out/biclique_10_3.csv').run()
# 極大2部クリークの結果を閲覧する
biclique = pd.read_csv('out/biclique_10_3.csv')
biclique

                                        モニタ%0     商品%1  size1  size2
0     04g 069 06I 0S2 0XC 0hX 0oq 1xy 2rF 4zS   0 3o 5     10      3
1         04g 069 0Ac 0hX 2jS 2rF F4 PX if tf   0 1B 4     10      3
2          04g 069 0CQ 0ax 0hX G6 XT bj r6 tf   0 5J n     10      3
3        04g 069 0SV 0hX 1uU 4eX 4zS Gc XT if   0 3o n     10      3
4          04g 069 0SV 0hX 3zp A0 F4 PX if tf   0 1B n     10      3
..                                        ...      ...    ...    ...
98    0Yt 0t3 1Cc 1MZ 1a8 3Jr 3pV 6Q g9 r6 ut   0 08 4     11      3
99   0Yt 16Q 1SM 1sQ 2rF 2up 4zS 5YK 6Q r6 tf   0 1H 4     11      3
100      0Yt 16Q 1SM 2mo 2rF 4eX 5YK 9F qh tf  0 0H 1H     10      3
101    0ax 0hX 16Q 2jS 2up 3vu F4 g9 if r6 tf    0 4 c     11      3
102  0oq 16Q 19d 1xy 2rF 2up 3s4 4gH 76 g9 pt    0 1 g     11      3

[103 rows x 4 columns]

In [5]:
# 例題5.12の解答

df = pd.read_csv('in/datQpr.csv')  # QPRのデータを読み込む
df = df[df['業態名'] == 'スーパー']  # スーパーのみ選択
# 日本茶・麦茶ドリンクを買っているモニタ一覧を作る
sel = df[df['細分類名'] == '日本茶・麦茶ドリンク']['モニタ'].drop_duplicates()

# そのモニタのデータのみを選択する
df = df[df['モニタ'].isin(sel)]
# 全員が日本茶・麦茶ドリンクを購入しており、
# そのような商品を加えても意味がないので削除しておく
df = df[df['細分類名'] != '日本茶・麦茶ドリンク']
df['レシート'] = df['モニタ'].str.cat(df['日付'].astype(str))
bigraph = df[['レシート', '細分類名']].drop_duplicates()
bigraph.to_csv('out/bigraph2.csv', index=False)

print(bigraph)
print('モニタ数:', len(sel))
print('商品数:', len(bigraph['細分類名'].drop_duplicates()))
print('2部グラフ全行数:', len(bigraph))

# l=にモニタ集合と商品集合の最小サイズを指定することが可能
nt.mbiclique(ei='out/bigraph2.csv', ef='レシート,細分類名',
             l='50,3', o='out/biclique2.csv').run()
biclique2 = pd.read_csv('out/biclique2.csv')
biclique2

               レシート            細分類名
1123    04g20140228             ビール
1127    04g20131205              つゆ
1130    04g20140412         衣料用合成洗剤
1131    04g20131008              豆腐
1134    04g20140207           ヨーグルト
...             ...             ...
222989   uy20140105       インスタントスープ
222990   uy20130919  香辛料（からし・わさび以外）
222991   uy20140105           その他雑酒
222992   uy20140105           その他水産
222993   uy20140105              豆腐

[69577 rows x 2 columns]
モニタ数: 192
商品数: 488
2部グラフ全行数: 69577

,レシート%0,細分類名%1,size1,size2
0,04g20130604 04g20130614 04g20130625 04g2013062...,その他農産 ヨーグルト 食パン,266,3
1,04g20130604 09a20140113 0C120140216 0RU2013110...,その他農産 スポーツドリンク ヨーグルト,64,3
2,04g20130605 04g20130629 04g20130814 04g2014010...,その他農産 つゆ 生麺・ゆで麺,63,3
3,04g20130605 04g20140215 04g20140227 04g2014032...,その他農産 半生菓子 生麺・ゆで麺,62,3
4,04g20130606 04g20130617 04g20130627 04g2013082...,その他農産 納豆 食パン,283,3
...,...,...,...,...
621,0dC20131026 0rn20140331 16Q20140412 17n2013061...,チョコレ−ト 納豆 菓子パン,69,3
622,0oq20130924 0rn20130625 0rn20130911 0rn2013111...,半生菓子 生菓子 食パン,57,3
623,0rn20130613 0rn20130625 0rn20130629 0rn2013080...,牛乳 生菓子 菓子パン,61,3
624,0t320130814 0t320131012 0t320140425 0t32014052...,ヨーグルト 牛乳 菓子パン 食パン,52,4
625,17n20130804 1SM20130905 1kt20140525 3Bv2013111...,漬物 納豆 野菜ジュース,54,3